Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Register=Erabiltzailea Erregistratu
MainGUI.Login=Saioa Hasi
MainGUI.VerAceptadas=Onartutako Salmentak Ikusi
MainGUI.Billetera = Nire Diru-zorroa

LoginGUI.Title=Saioa Hasi
LoginGUI.Email=Posta elektronikoa:
LoginGUI.Password=Pasahitza:
LoginGUI.LoginButton=Sartu
LoginGUI.ErrorEmpty=Errorea: Eremu guztiak bete behar dira.
LoginGUI.ErrorLogin=Errorea: Kredentzial okerrak.
LoginGUI.Success=Saioa ondo hasi da! Ongi etorri.

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da

RegisterGUI.Title=Erabiltzailea Erregistratu
RegisterGUI.Name=Izena:
RegisterGUI.Email=Posta elektronikoa:
RegisterGUI.Password=Pasahitza:
RegisterGUI.RepeatPassword=Pasahitza Errepikatu:
RegisterGUI.Seller=Saltzailea
RegisterGUI.Buyer=Eroslea
RegisterGUI.RegisterButton=Erregistratu
RegisterGUI.Success=Erabiltzailea ondo erregistratu da!
RegisterGUI.ErrorEmpty=Errorea: Eremu guztiak bete behar dira.
RegisterGUI.ErrorPass=Errorea: Pasahitzak ez datoz bat.
RegisterGUI.ErrorEmail=Errorea: Posta elektronikoa erabilita dago jada.

VIP.Title=VIP bihurtu
VIP.Header=Hobetu zure kontua VIP izateko!
VIP.Benefits=<html><ul><li>Zure izena urre kolorez nabarmenduko da.</li><li>Zure eskaintzak lehentasuna izango dute.</li><li>24/7 Laguntza.</li></ul></html>
VIP.Price=Prezioa: 5.00 \u20AC / hilean
VIP.BuyButton=Erosi Harpidetza
VIP.Success=Zorionak! Dagoeneko VIP erabiltzailea zara.
VIP.Error=Errorea: Ez duzu diru nahikorik edo dagoeneko VIP zara.

MainGUI.VIPButton=\u2B50 VIP bihurtu
MainGUI.LogoutButton=Saioa Itxi
MainGUI.Balance=\uD83D\uDCB0 Nire Saldoa:

MainGUI.MyRating=\u2605 Nire Balorazioa:
MainGUI.NoVotes=Botorik ez